'use strict';
const $=id=>document.getElementById(id);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let playing=!reduced, mode='block',time=0,speed=1;
const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(38,1,.1,500);camera.position.set(34,28,38);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;renderer.setClearColor(0xdce2d2,0);renderer.outputColorSpace=THREE.SRGBColorSpace;
$('canvas-host').appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Schematic 3D plant model');
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enableZoom=false;controls.minDistance=15;controls.maxDistance=125;controls.target.set(0,4,0);controls.maxPolarAngle=Math.PI*.95;
scene.add(new THREE.HemisphereLight(0xffffff,0x6c7861,2.6));const sun=new THREE.DirectionalLight(0xfff8e7,3.2);sun.position.set(-15,35,20);scene.add(sun);
const plant=new THREE.Group();scene.add(plant);
const mats=[],layers=[],rotors=[],dots=[];const groups={shell:[],core:[],pipes:[],machines:[]};
const palette={concrete:0xaaa994,roof:0x899281,edge:0x697360,graphite:0x46514b,steel:0xabb8a1,water:0x609b99,steam:0xb9865d,dark:0x384c41,glass:0x637e75};
const materialCache=new Map();
function material(color){if(materialCache.has(color))return materialCache.get(color);const m=new THREE.MeshStandardMaterial({color,roughness:.82,metalness:.16});mats.push(m);materialCache.set(color,m);return m}
function layer(system,y,rank){let g=new THREE.Group();g.position.y=y;g.userData={base:y,rank,system};plant.add(g);layers.push(g);groups[system].push(g);return g}
function box(g,w,h,d,x,y,z,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(c));m.position.set(x,y,z);g.add(m);return m}
function cyl(g,r,h,x,y,z,c,r2=r){const m=new THREE.Mesh(new THREE.CylinderGeometry(r2,r,h,20),material(c));m.position.set(x,y,z);g.add(m);return m}
function pipe(g,pts,r,c){const curve=new THREE.CatmullRomCurve3(pts.map(p=>new THREE.Vector3(...p)),false,'catmullrom',.1);const m=new THREE.Mesh(new THREE.TubeGeometry(curve,32,r,8,false),material(c));g.add(m);return curve}
function rod(g,a,b,r,c){const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b);const v=B.clone().sub(A);const m=cyl(g,r,v.length(),...A.clone().add(B).multiplyScalar(.5).toArray(),c);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());return m}
const base=layer('core',0,0);box(base,29,.65,21,0,-.3,0,0x9eaa91);box(base,30,.15,22,0,-.68,0,0xc0c8b2);
// Exterior: a compact two-volume teaching interpretation of a power block.
const shell=layer('shell',0,5.5);box(shell,11,10,.4,-4,5,-5.7,palette.concrete);box(shell,.4,10,11,-9.5,5,-.3,palette.concrete);box(shell,.4,10,11,1.5,5,-.3,palette.concrete);box(shell,11,3,.35,-4,1.5,5.2,palette.concrete);box(shell,11,3,.35,-4,8.5,5.2,palette.concrete);
for(let x=-9;x<1;x+=1.1){box(shell,.13,4,.5,x,5,5.2,palette.edge);box(shell,.84,3.7,.12,x+.48,5,5.22,palette.glass)}
for(let z=-5;z<5;z+=1.1){box(shell,.12,1.4,.75,1.72,8.4,z,palette.glass);box(shell,.12,2.4,.75,1.72,4,z,palette.glass)}
const hall=layer('shell',0,2.8);box(hall,8,4,.3,7,2,-8.5,palette.concrete);box(hall,.3,4,17,11,2,0,palette.concrete);box(hall,8,2,.3,7,1,8.5,palette.concrete);for(let z=-8;z<=8;z+=1.1){box(hall,.15,1.4,.75,11.17,2.9,z,palette.glass);box(hall,8,.15,.13,7,3.9,z,palette.steel)}
const roofs=layer('shell',0,8);box(roofs,11.8,.45,11.8,-4,10.2,-.2,palette.roof);box(roofs,8.7,.3,17.8,7,4.2,0,palette.roof);for(let z=-7;z<8;z+=1.4)box(roofs,8.5,.12,.07,7,4.42,z,palette.edge);box(roofs,4,.75,5,-4,10.75,0,palette.concrete);for(let z=-2;z<3;z++)box(roofs,3.5,.1,.35,-4,11.18,z,palette.glass);
const tower=layer('shell',0,.4);cyl(tower,.48,20,-10.5,10,-7.8,palette.concrete);for(let h=0;h<20;h+=2.5){const r=1.25;for(let s=0;s<4;s++){let a=s*Math.PI/2,b=(s+1)*Math.PI/2;const p=[-10.5+Math.cos(a)*r,h,-7.8+Math.sin(a)*r],q=[-10.5+Math.cos(b)*r,h+2.5,-7.8+Math.sin(b)*r];rod(tower,p,q,.055,palette.edge);rod(tower,p,[p[0],h+2.5,p[2]],.07,palette.edge);rod(tower,p,[q[0],h,q[2]],.05,palette.edge)}}cyl(tower,.57,.6,-10.5,20,-7.8,palette.dark);
const lower=layer('core',0,.1);cyl(lower,4,.85,-4,1.1,0,palette.concrete);box(lower,8.5,.6,8.5,-4,.7,0,palette.steel);
const stack=layer('core',0,1.4);for(let x=-7;x<=-1;x+=.7)for(let z=-3;z<=3;z+=.7){box(stack,.65,4.6,.65,x,3.8,z,palette.graphite);cyl(stack,.10,5.1,x,4,z,palette.steam)}
const shield=layer('core',0,2.7);cyl(shield,4.05,.7,-4,6.7,0,palette.steel);for(let x=-6.8;x<-.9;x+=.75)for(let z=-2.8;z<3;z+=.75)if((x+4)**2+z*z<12)cyl(shield,.13,.22,x,7.16,z,palette.dark);
const drums=layer('pipes',0,4);for(const z of [-3.5,3.5]){let drum=cyl(drums,.68,7,-4,8.4,z,palette.steel);drum.rotation.z=Math.PI/2;for(let x=-7;x<=-1;x+=1.5){pipe(drums,[[x,7.3,z*.55],[x,7.9,z],[x,8.4,z]],.075,palette.steam)}}
const plumbing=layer('pipes',0,1.9);for(let z of [-4.4,4.4]){pipe(plumbing,[[-7,8.4,z*.8],[-8,8.4,z],[-8,1.8,z],[-5,1.8,z],[-5,1.2,0]],.17,palette.water);pipe(plumbing,[[-1,8.4,z*.8],[2,8.4,z],[3,6,z],[6,6,z],[6,3,z]],.2,palette.steam)}
const machinery=layer('machines',0,.65);for(let z of [-4.5,4.5]){box(machinery,4,.5,5,6,1,z,palette.concrete);const turbine=cyl(machinery,1.05,3.6,6,2.4,z,palette.steel);turbine.rotation.x=Math.PI/2;const shaft=rod(machinery,[6,2.4,z-2.6],[6,2.4,z+2.6],.14,palette.dark);const rotor=new THREE.Group();rotor.position.set(6,2.4,z);machinery.add(rotor);for(let a=0;a<12;a++){const blade=box(rotor,.13,1.6,.15,0,0,0,palette.steam);blade.rotation.z=a*Math.PI/6;}rotors.push(rotor);let gen=cyl(machinery,.73,1.35,6,2.4,z+2.6,palette.water);gen.rotation.x=Math.PI/2;box(machinery,2,1,2.8,6,.7,z,palette.water)}for(let z of [-4,4]){cyl(machinery,.6,1.5,-8,1.5,z,palette.water);cyl(machinery,.4,.5,-8,2.5,z,palette.dark)}
const grid=new THREE.GridHelper(40,40,0xb1bba5,0xc8d0bd);grid.position.y=-.79;scene.add(grid);
// Animated schematic cutaway with explicit graphite, pressure tubes, drums and circulation.
const motion=new THREE.Group();scene.add(motion);motion.visible=false;
box(motion,11,.7,10,0,0,0,palette.concrete);box(motion,9,7,1,0,4,-3.7,palette.graphite);box(motion,1,7,7,-4,4,0,palette.graphite);for(let x=-3;x<=3;x+=1)for(let z=-2;z<=2;z+=1){cyl(motion,.16,6.8,x,4,z,palette.steel);cyl(motion,.06,6.4,x+.20,4,z,palette.steam)}
box(motion,9,.5,8,0,7.7,0,palette.steel);motion.children.forEach(o=>o.userData.system='core');for(let z of [-3,3]){const d=cyl(motion,.8,8,0,9.5,z,palette.steel);d.rotation.z=Math.PI/2}
function particles(g,curve,color,count){for(let i=0;i<count;i++){const dot=new THREE.Mesh(new THREE.SphereGeometry(.105,7,7),new THREE.MeshBasicMaterial({color}));g.add(dot);dot.position.copy(curve.getPointAt(i/count));dots.push({dot,curve,offset:i/count})}}
for(let x=-3;x<=3;x++){const route=pipe(motion,[[x,1,0],[x,6.8,0],[x,8.4,1],[x,9.5,3]],.08,palette.water);particles(motion,route,0xc9f6ed,7)}
const down=pipe(motion,[[3,9.5,-3],[6,9.5,-3],[6,1,-3],[0,1,-3],[0,1,0]],.24,palette.water);particles(motion,down,0xc4f8f1,20);
const steam=pipe(motion,[[3,9.5,3],[8,9.5,3],[9,4,3],[11,4,3]],.25,palette.steam);particles(motion,steam,0xffdfb2,15);
motion.children.forEach(o=>{if(!o.userData.system)o.userData.system='pipes'});
const mr=new THREE.Group();mr.position.set(11,4,3);motion.add(mr);rod(motion,[11,4,1],[11,4,5],.2,palette.dark);for(let i=0;i<10;i++){const b=box(mr,.18,3,.3,0,0,0,palette.steel);b.rotation.z=i*Math.PI/5}rotors.push(mr);cyl(motion,.85,1.7,6,1.8,-3,palette.water);box(motion,4,.6,5,11,.2,3,palette.concrete);motion.children.forEach(o=>{if(!o.userData.system){o.userData.system='machines';o.traverse(c=>c.userData.system='machines')}});
const labelDefs=[['Reactor building',[-4,10.8,0],shell],['Turbine hall',[8,5,5],roofs],['Ventilation stack',[-10.5,18,-7.8],tower],['Graphite stack',[-4,4,0],stack],['Separator drums',[-4,9,3.5],drums]];
for(const [name,p,g] of labelDefs){const el=document.createElement('span');el.className='label';el.textContent=name;$('labels').appendChild(el);g.userData.label={el,p:new THREE.Vector3(...p)}}
const status=t=>$('status').textContent=t;
let previousFit=1;
function update(){const ex=+$('explode').value/100,sp=+$('spacing').value/10;for(const g of layers){g.position.y=g.userData.base+ex*sp*g.userData.rank*2;g.visible=$(g.userData.system).checked}for(const m of mats){m.wireframe=$('wire').checked;m.transparent=$('transparent').checked;m.opacity=m.transparent?.36:1;m.depthWrite=!m.transparent;m.clippingPlanes=$('section').checked?[new THREE.Plane(new THREE.Vector3(0,0,-1),0)]:[];m.needsUpdate=true}$('explode-value').textContent=Math.round(ex*100)+'%';$('spacing-value').textContent=sp.toFixed(1)+'×';if(mode==='block'){const fit=1+ex*sp*.28;const offset=camera.position.clone().sub(controls.target).multiplyScalar(fit/previousFit);controls.target.set(0,4+ex*sp*8,0);camera.position.copy(controls.target).add(offset);previousFit=fit}motion.traverse(o=>{if(o.isMesh){const system=o.userData.system||'core';o.visible=$(system).checked}});mr.visible=$('machines').checked;}
function resize(){const w=$('viewport').clientWidth,h=$('viewport').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}
new ResizeObserver(resize).observe($('viewport'));
function reset(){previousFit=1;camera.position.set(innerWidth<640?43:34,innerWidth<640?36:28,innerWidth<640?49:38);controls.target.set(0,4,0);$('explode').value=0;update();controls.update();status('View reset · assembled')}
function setMode(next){mode=next;$('viewport').classList.toggle('circuit-mode',next==='circuit');for(const n of ['block','circuit','motion']){$('tab-'+n).setAttribute('aria-selected',String(n===next));$('tab-'+n).tabIndex=n===next?0:-1}plant.visible=next==='block';motion.visible=next==='motion';grid.visible=next!=='circuit';$('canvas-host').hidden=next==='circuit';$('circuit').hidden=next!=='circuit';$('labels').hidden=next!=='block';const titles={block:['RBMK–1000 / POWER BLOCK','Anatomy of a power station','FIG. 01','Start with the whole, then pull it apart. The long turbine hall sits beside the taller reactor building; inside, fuel channels pass through a graphite moderator.'],circuit:['HEAT → MOTION → ELECTRICITY','Follow the energy','FIG. 02','Copper traces steam; teal traces returning water. Separator drums return liquid to the core. The condenser transfers waste heat to a separate cooling-water loop.'],motion:['RBMK–1000 / CORE CUTAWAY','A system in circulation','FIG. 03','Water rises through the fuel channels, partly boiling. Steam separates above the core; liquid recirculates. Moving particles and rotor speeds illustrate direction, not operating conditions.']};['view-kicker','view-title','caption-number','caption'].forEach((id,i)=>$(id).textContent=titles[next][i]);$('view-hint').textContent=next==='circuit'?(innerWidth<640?'Swipe diagram ↔ · Copper: steam · Teal: water':'Copper: steam · Teal: water · G: generator'):'↔ Drag to orbit · Scroll to separate · + / − to zoom';$('explode').disabled=next!=='block';$('spacing').disabled=next!=='block';for(const id of ['shell','wire','transparent','section','label-toggle'])$(id).disabled=next==='circuit'||(next==='motion'&&(id==='shell'||id==='label-toggle'));reset();if(next==='motion'){camera.position.set(24,21,30);controls.target.set(2,5,0)}status({block:'Power Block · assembled',circuit:'Steam Circuit · follow the closed loop',motion:'Reactor in Motion · illustrative flow'}[next]);}
for(const n of ['block','circuit','motion'])$('tab-'+n).onclick=()=>setMode(n);
document.querySelector('.tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const ns=['block','circuit','motion'];let i=ns.indexOf(mode);i=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setMode(ns[i]);$('tab-'+ns[i]).focus()});
for(const id of ['explode','spacing'])$(id).oninput=()=>{update();status(id==='explode'?'Disassembly · '+$('explode').value+'%':'Layer spacing · '+$('spacing-value').textContent)};
for(const id of ['shell','core','pipes','machines','wire','transparent','section','label-toggle'])$(id).onchange=()=>{update();const names={shell:'Building envelope',core:'Core & shielding',pipes:'Steam & water',machines:'Turbines & pumps',wire:'Wireframe',transparent:'Transparency',section:'Section cut','label-toggle':'Labels'};status(names[id]+' · '+($(id).checked?'on':'off'));if(mode==='circuit'){const s=$('circuit');s.querySelectorAll('.flow').forEach(x=>x.style.visibility=$('pipes').checked?'visible':'hidden');s.querySelectorAll('.turbine-shape,.shaft').forEach(x=>x.style.visibility=$('machines').checked?'visible':'hidden');s.querySelector('rect').style.visibility=$('core').checked?'visible':'hidden'}};
$('reset').onclick=reset;
function playback(){ $('play').textContent=playing?'Pause motion Ⅱ':'Play motion ▷';$('circuit').classList.toggle('paused',!playing)}
$('play').onclick=()=>{playing=!playing;playback();status(playing?'Motion playing':'Motion paused')};$('speed').onchange=()=>{speed=+$('speed').value;document.querySelectorAll('.flow').forEach(p=>p.style.animationDuration=2/speed+'s');status('Playback speed · '+speed+'×')};playback();
$('viewport').addEventListener('wheel',e=>{if(mode!=='block')return;e.preventDefault();$('explode').value=Math.max(0,Math.min(100,+$('explode').value+Math.sign(e.deltaY)*4));$('explode').dispatchEvent(new Event('input'))},{passive:false});
$('viewport').addEventListener('keydown',e=>{if(e.target!==$('viewport'))return;const v=camera.position.clone().sub(controls.target);if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const spherical=new THREE.Spherical().setFromVector3(v);spherical.theta+=(e.key==='ArrowLeft'?.13:e.key==='ArrowRight'?-.13:0);spherical.phi=Math.max(.15,Math.min(3,spherical.phi+(e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0)));camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(spherical));status('Camera rotated')}if(['+','=','-'].includes(e.key)){e.preventDefault();camera.position.copy(controls.target).add(v.multiplyScalar(e.key==='-'?1.1:.9));status('Camera zoom adjusted')}});
// Pinch zoom while one-finger dragging remains orbit control.
const touches=new Map();let pinch=0;$('viewport').addEventListener('pointerdown',e=>{touches.set(e.pointerId,[e.clientX,e.clientY]);if(touches.size===2){const [a,b]=[...touches.values()];pinch=Math.hypot(a[0]-b[0],a[1]-b[1])}});$('viewport').addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,[e.clientX,e.clientY]);if(touches.size===2){const[a,b]=[...touches.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(pinch>0){const v=camera.position.clone().sub(controls.target).multiplyScalar(pinch/d);v.clampLength(15,125);camera.position.copy(controls.target).add(v)}pinch=d}});for(const type of ['pointerup','pointercancel'])window.addEventListener(type,e=>touches.delete(e.pointerId));
const feedback={a:'Not quite. Steam is water vapor, not a new fuel. The key is how boiling changes neutron absorption.',b:'Correct. Less liquid water could mean less neutron absorption while graphite continued moderating, reinforcing the power rise.',c:'Not quite. The feedback was inside the reactor: boiling changed neutron absorption. The turbine did not electrically heat the fuel.'};for(const n of ['a','b','c'])$('answer-'+n).onclick=()=>{for(const x of ['a','b','c'])$('answer-'+x).setAttribute('aria-pressed',String(x===n));$('quiz-feedback').textContent=feedback[n]};
let inView=true;new IntersectionObserver(entries=>inView=entries[0].isIntersecting).observe($('viewport'));
let last=0;function frame(now){requestAnimationFrame(frame);if(now-last<33||!inView)return;const dt=Math.min((now-last)/1000,.05);last=now;if(playing){time+=dt*speed;rotors.forEach(r=>r.rotation.z=time*1.8);dots.forEach(d=>d.dot.position.copy(d.curve.getPointAt((time*.10+d.offset)%1)))}controls.update();for(const g of layers){const l=g.userData.label;if(!l)continue;const show=$('label-toggle').checked&&g.visible&&((g!==stack&&g!==drums)||+$('explode').value>25||!$('shell').checked||$('transparent').checked);l.el.hidden=!show;const p=l.p.clone();p.y+=g.position.y;p.project(camera);l.el.style.left=(p.x*.5+.5)*$('viewport').clientWidth+'px';l.el.style.top=(-p.y*.5+.5)*$('viewport').clientHeight+'px';if(p.z>1)l.el.hidden=true}if(mode!=='circuit')renderer.render(scene,camera)}reset();resize();status('Power Block · assembled');requestAnimationFrame(frame);
